.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. sarielsaz_qt test_sarielsaz_qt
clean: FORCE
	$(MAKE) -C .. sarielsaz_qt_clean test_sarielsaz_qt_clean
check: FORCE
	$(MAKE) -C .. test_sarielsaz_qt_check
sarielsaz-qt sarielsaz-qt.exe: FORCE
	 $(MAKE) -C .. sarielsaz_qt
